### ISSUE TITLE
Inconsistent OPEN/CLOSE states

### ISSUE THREAD

**Issue by cipherthinkers** [StefanoMartella/react-native-simple-bottom-sheet#11]
**Try the following**:
- On click of a button, open the bottom sheet
- Now instead of clicking on the same button or clicking on the sheet top line, slide down to close the sheet
- Click on the button again, it will not open the sheet, rather you will get a callback in onClose method. Clicking on the button for the second time will open the sheet.

**Comment by StefanoMartella** [comment]
Hi @cipherthinkers,

can you please provide some code? TY

**Comment by cipherthinkers** [comment]
Sure @StefanoMartella 

I'm using functional component. Here is the concerned code:


```
<BottomSheet
    isOpen={false}
    sliderMinHeight={0}
    sliderMaxHeight={screenHeight}
    ref={myBottomSheetRef}>
          <View>
                 <ScrollView>
                        ...Other views here
                 </ScrollView>
          </View>
</BottomSheet>
```

I've a button on click of which I'm doing the following

```
myBottomSheetRef?.current?.togglePanel()
```

After the button click, when the sheet opens - I'm sliding down on my content in the bottom sheet. This is closing the bottom sheet. Till now, everything is fine. 

Then on click of this button, the sheet doesn't open. Rather the onClose hook of the sheet gets called. Next time when I click on it, it gets opened.

**Comment by StefanoMartella** [comment]
Hi @cipherthinkers,

Sorry for the late response but I've been busy these days.
Anyway, I tried to reproduce your problem with no luck.

Here you can see an example of what I get:

<div>
<img src="https://user-images.githubusercontent.com/29805626/180452924-839bb181-5fb1-4415-bb38-f08d9d062d74.gif" width="100%" />
</div>

<br />

The code is the following:

```javascript
const App = () => {
  const panelRef = useRef();

  return (
    <ScrollView contentContainerStyle={styles.container}>
      <TouchableOpacity
        activeOpacity={0.8}
        style={styles.button}
        onPress={() => panelRef.current?.togglePanel()}>
        <Text>Toggle</Text>
      </TouchableOpacity>
      <View style={styles.content}>
        <BottomSheet
          ref={panelRef}
          isOpen={false}
          onOpen={() => console.log('Opened')}
          onClose={() => console.log('Closed')}
          sliderMaxHeight={Dimensions.get('window').height * 0.8}>
          {onScrollEndDrag => (
            <>
              <View style={styles.headerContainer}>
                <Text style={styles.title}>Title</Text>
                <Text style={styles.subTitle}>Subtitle</Text>
              </View>
              <ScrollView onScrollEndDrag={onScrollEndDrag}>
                {[...Array(10)].map((_, index) => (
                  <TouchableOpacity key={index} style={styles.listItem}>
                    <Text>{`List Item ${index + 1}`}</Text>
                  </TouchableOpacity>
                ))}
              </ScrollView>
            </>
          )}
        </BottomSheet>
      </View>
    </ScrollView>
  );
};
```
<br />

Just to be sure, in the onClick prop of your button, are you passing an arrow function or the reference of the `togglePanel` method? In the second case, try what I did instead
