### ISSUE TITLE
backgroundColor in bottomsheet not working...

### ISSUE THREAD

**Issue by Lucstay11** [StefanoMartella/react-native-simple-bottom-sheet#13]
I would like ot change the bottom sheet background color an is not working

`<BottomSheet isOpen animationDuration={100} style={{backgroundColor:"blue"}}>
         <Slider style={{width: "100%", height: 20}} minimumValue={1} maximumValue={100} value={20}  minimumTrackTintColor="green" maximumTrackTintColor="green" thumbTintColor="green"/>
         </BottomSheet>`

**Comment by StefanoMartella** [comment]
Hi @Lucstay11, you should use `wrapperStyle` or `outerContentStyle` or `innerContentStyle` instead of `style` based on your needs

**Comment by Lucstay11** [comment]
Okay and I tried to add a webView but it is not displayed... Have you already tried??

**Comment by StefanoMartella** [comment]
I've never tried to display a webview within the bottom sheet; have you tried to force the `width` and the `height` of the webview by setting them through props?

**Comment by Lucstay11** [comment]
Yes i do this 
`<View  style={{ flex: 1}}>
     <WebView source={{ uri: "https://google.com" }} 
          javaScriptEnabled={true}
          startInLoadingState={true}
          injectedJavaScript={jsCode}
          />
     </View>`

but he doesn't work...
I used your project because it is simpler to set up than that of BottomSheet from "@gorhom/bottom-sheet"
(everything worked well with it but not the slide and gesture movements) so I tried yours and it's cool but the webView doesn't work. Can you try your odds please?

**Comment by StefanoMartella** [comment]
Hi @Lucstay11,

have you tried to force te `height` of the `View` that wraps the `BottomSheet` component?

With the following code I see the webview:

```js
import { useRef } from 'react';
import { Text, TouchableOpacity, View } from 'react-native';
import BottomSheet from 'react-native-simple-bottom-sheet'
import WebView from 'react-native-webview';

export default function App() {
  const ref = useRef();

  return (
    <View style={{ backgroundColor: '#dedede', flex: 1 }}>
      <TouchableOpacity
        style={{ marginTop: 50, alignSelf: 'center', padding: 10, backgroundColor: 'green', borderRadius: 10 }}
        onPress={() => ref.current.togglePanel()}
      >
        <Text style={{ color: 'white' }}>Toggle</Text>
      </TouchableOpacity>
      <BottomSheet ref={ref}>
        <View style={{ height: 500 }}>
          <WebView 
            source={{ uri: "https://google.com" }}
            javaScriptEnabled={true}
            startInLoadingState={true}
          />
        </View>
      </BottomSheet>
    </View>
  );
}
```

https://github.com/StefanoMartella/react-native-simple-bottom-sheet/assets/29805626/a24a4215-b7bb-4306-8b23-444d5609429c

**Comment by Lucstay11** [comment]
Yes it works now but the webView does not want to put it in flex1 (in 100% width) and I noticed that your bottom sheet is not scrollable for opening/closing it closes directly! (Can you add this scrollable effect like the 1st one in the video)

The first in the video comes from @gorhom/bottom-sheet it is perfect but prevents the gesture and the scrollview!

` <BottomSheet ref={ref} isOpen>
        <View style={{ height:1000,flex:1}}>
        <Weather/>
        </View>
      </BottomSheet>
`


https://github.com/StefanoMartella/react-native-simple-bottom-sheet/assets/89875785/fadacab7-895c-404f-9dba-01b31b78bf0f

**Comment by StefanoMartella** [comment]
To make the content to take the whole width you need to remove the `paddingHorizontal` from the wrapper:

```js

<BottomSheet wrapperStyle={{ paddingHorizontal: 0 }} />

```

Unfortunately I have no time to add the animation; feel free to contribute to the project 😄
