### ISSUE TITLE
Stop closing of panel on clicking children

### ISSUE THREAD

**Issue by ShashwatMDas** [StefanoMartella/react-native-simple-bottom-sheet#2]
I want to add a form to the panel. It works fine when I open it for the first time, but as if I click on it again, it starts closing whenever I try to click on any field. Any solution?

**Comment by StefanoMartella** [comment]
Hi @ShashwatMDas. I'll check it in the afternoon If I'll have a bit of free time from work. I'll update you

**Comment by StefanoMartella** [comment]
Hi @ShashwatMDas. I tried to reproduce the behaviour you described with no luck, can you please provide some code? This is the behaviour I get:

<br />
<p align="center">
  <img src="https://user-images.githubusercontent.com/29805626/94829167-886d9880-040a-11eb-896f-783a0c15c85d.gif" alt="toggle"  width="30%">
</p>
<br />
