### ISSUE TITLE
Add option to blur/darken the rest of the screen

### ISSUE THREAD

**Issue by Thiousi** [StefanoMartella/react-native-simple-bottom-sheet#3]
Hello @StefanoMartella ,
I'm trying to understand how I could, the same way a modal would do it, darken and blur the rest of the screen when the bottom sheet is opened. Can I use isOpen?
Thanks a lot!

**Comment by StefanoMartella** [comment]
Hello @Thiousi, thank for using this library.
I've just released a alpha version that implements the modal behaviour you described; the implementation relies on a `react-native-portalize` module.

Example of usage:

```javascript
// other imports
import BottomSheet from 'react-native-simple-bottom-sheet';
import {Host, Portal} from 'react-native-portalize';

const App = () => {
  return (
    <Host>
      <SafeAreaView>
        <StatusBar barStyle="light-content" />
        <ScrollView
          contentContainerStyle={styles.container}
          contentInsetAdjustmentBehavior="automatic">
          <View style={styles.content}>
            <Portal>
              <BottomSheet withOverlay isOpen={false}>
                {(onScrollEndDrag) => (
                  <ScrollView onScrollEndDrag={onScrollEndDrag}>
                    {[...Array(10)].map((_, index) => (
                      <TouchableOpacity
                        key={`${index}`}
                        onPress={() => console.log(index + 1)}
                        style={styles.listItem}>
                        <Text>{`List Item ${index + 1}`}</Text>
                      </TouchableOpacity>
                    ))}
                  </ScrollView>
                )}
              </BottomSheet>
            </Portal>
          </View>
        </ScrollView>
      </SafeAreaView>
    </Host>
  );
};
```

The `Host` component most likely should wrap your whole app; the `Portal` component must wrap the `BottomSheet` (also pass the `withOverlay` prop to it).

The result should be something like this:

<div>
<img src="https://user-images.githubusercontent.com/29805626/114318726-a1b87580-9b0e-11eb-9234-6a31161405a9.gif"  width="40%"/>
</div>

Waiting your feedback! :smile:

**Comment by Thiousi** [comment]
Thanks a lot for the quick reply @StefanoMartella 

I was able to get a barebones snack working with your example and version 1.1.0-alpha0
[https://snack.expo.io/@thiousi/react-native-simple-bottom-sheet-portalize
](https://snack.expo.io/@thiousi/react-native-simple-bottom-sheet-portalize
)It's working just as expected, awesome! Note: doesn't display well on the web, I ran it on my device without issue.

Now, I need to make it work in my app and I haven't had any luck so far.  I'll keep at it!
Got it working! I somehow needed to relaunch the expo app on my phone a couple of times and it's now working great!

**Comment by Thiousi** [comment]
Hello again @StefanoMartella 
So the fix I found for the other issue with the excessive unmounting is now preventing host/portal from displaying the overlay.

I have wrapped the stack navigator with Host and my Menu Button and BottomSheet like so:
```javascript
    return (
      <NavigationContainer ref={navigationRef}>
        <Host>
          <MenuButton/>
          
          <Stack.Navigator 
            initialRouteName="Accueil"
            screenOptions={{
              headerShown: false
            }}>
            <Stack.Screen name="Accueil" component={CarouselScreen}/>
            <Stack.Screen name="Liste" component={WordIndexScreen}/>
            <Stack.Screen name="Favoris" component={FavoritesScreen}/>
            <Stack.Screen name="Réglages" component={SettingsScreen}/>
            <Stack.Screen name="Partager" component={SharingScreen}/>
          </Stack.Navigator>
          
          <BottomMenu />
        </Host>
      </NavigationContainer>
    );
```
From the [react-native-portalize](https://github.com/jeremybarbet/react-native-portalize) page it seems like an appropriate way of doing it but I'm not seeing the overlay anymore. Have you tried implementing this with your alpha version?

**Comment by StefanoMartella** [comment]
Hello again 😄 

try to move the `Host` component outside the navigator, most likely it should be highest (or almost) component in the hierarchy.

EDIT:
Btw, to answer your question, I tested it and it's working fine. My code is something like:

```javascript
// RootNavigator.js

const Stack = createStackNavigator();

function RootNavigator() {
  return (
    <NavigationContainer>
      <Stack.Navigator>
          <Stack.Screen name="DrawerNavigator" component={DrawerNavigator} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
```

```javascript
// DrawerNavigator.js

const Drawer = createDrawerNavigator();

function DrawerNavigator() {
  const {user} = useSelector((state) => state.account);

  return (
    <Drawer.Navigator
      drawerType="front"
      headerMode="screen"
      drawerContent={(props) => <DrawerScreen {...props} />}>
      <Drawer.Screen name="app" component={LoggedNavigator} />
    </Drawer.Navigator>
  );
}
```

```javascript
// LoggedNavigator

const LoggedStack = createStackNavigator();
const RoutesTabNavigator = createMaterialTopTabNavigator();

function LoggedNavigator() {
  const {user} = useSelector((state) => state.account);

  return (
    <Host>
      <LoggedStack.Navigator>
          <LoggedStack.Screen ... />
      </LoggedStack.Navigator>
    </Host>
}
```

Then inside one of the `LoggedStack.Screen` component I've the bottom sheet, the result is the following:

<div>
<img src="https://user-images.githubusercontent.com/29805626/114469493-912afc80-9bed-11eb-86c0-7d72f6d729a7.gif" width="40%" />
</div>

**Comment by StefanoMartella** [comment]
Hi @Thiousi,
I hope you have solved your problem 🤞  I'm closing the issue since it doens't seem to be related to the bottom sheet 😉
