### ISSUE TITLE
Bottom sheet inside scroll view 

### ISSUE THREAD

**Issue by MamtaDeswal-BB** [StefanoMartella/react-native-simple-bottom-sheet#5]
Content not scroll inside bottom sheet when we put bottom sheet inside scroll view.

**Comment by StefanoMartella** [comment]
Hi,

can you please provide a code example? 😄 

Anyway you can try something like the following (if it fits with your case):

```javascript
<View>
   <ScrollView>
     // Your scrollable content
   </ScrollView>
   <BottomSheet>
     // Your bottom sheet content
   </BottomSheet>
</View>
```
