### ISSUE TITLE
Scroll view problems inside bottom sheet

### ISSUE THREAD

**Issue by mateobencek** [StefanoMartella/react-native-simple-bottom-sheet#6]
Hello,
I am trying to use this component as a wrapper around view with title, subtitle, and scroll view below.
Scroll view can't be used when minimal height is reached, and it is very sensitive on touches when on maximum height.
I want this component to be "always" open. So minimal height and maximum height will always display contents, but the maximum height will show more of course.
Another way to solve my problem would be to make only the top part of the component switching the heights.
Thanks in advance.

**Comment by StefanoMartella** [comment]
Hi @MrHighTech,

If I understood correctly you want something like this:

<div>
<img src="https://user-images.githubusercontent.com/29805626/128481860-acc1a646-ce8f-4161-bc24-a5ce9d04a93e.gif" width="40%" />
</div>

<br />

If so, you could do the following:


```javascript


<BottomSheet ref={panelRef} withOverlay={true} isOpen={true} sliderMinHeight={120}>
  {(onScrollEndDrag) => (
    <>
      <View>
        <Text>Title</Text>
        <Text>Subtitle</Text>
      </View>
      <ScrollView onScrollEndDrag={onScrollEndDrag}>
        {[...Array(10)].map((_, index) => (
          <TouchableOpacity
            key={${index}}
            onPress={() => console.log(index + 1)}
            style={styles.listItem}>
            <Text>{List Item ${index + 1}}</Text>
          </TouchableOpacity>
        ))}
      </ScrollView>
    </>
  )}
</BottomSheet>
```

<br />

Also, if you want only the top side of the bottom sheet to switch the heights just don't pass the `onScrollEndDrag` handler like this:

```javascript
<BottomSheet ref={panelRef} withOverlay={true} isOpen={true} sliderMinHeight={120}>
  <View>
    <Text>Title</Text>
    <Text>Subtitle</Text>
  </View>
  <ScrollView>
    {[...Array(10)].map((_, index) => (
      <TouchableOpacity
        key={${index}}
        onPress={() => console.log(index + 1)}
        style={styles.listItem}>
        <Text>{List Item ${index + 1}}</Text>
      </TouchableOpacity>
    ))}
  </ScrollView>
</BottomSheet>
```

<br />

in this case the result would be:

<div>
<img src="https://user-images.githubusercontent.com/29805626/128482675-af1cab46-07bb-4de2-9a58-81b4af16bf62.gif" width="40%" />
</div>

<br />

I hope this helps 😄

**Comment by mateobencek** [comment]
Actually, your maximum height in the preview would be my minimal height (~40% of the screen). And my maximum height would be ~70% of the screen. The problem is that when I lower the bottom sheet (at 40%), the scroll view is not scrollable nor items inside clickable (but those items are visible as I want).

**Comment by StefanoMartella** [comment]
Sorry but I can't reproduce your issue, this is what I get when I try to simulate what you described:

<div>
<img src="https://user-images.githubusercontent.com/29805626/128491040-86798cdc-2927-4e69-81cb-e1a0a1906826.gif" width="40%" />
</div>

<br />

Which version are you running? I've tested it on the alpha version
