### ISSUE TITLE
TextInput inside bottom sheet hide behind the keyboard in iOS

### ISSUE THREAD

**Issue by Zyauddin** [StefanoMartella/react-native-simple-bottom-sheet#7]
Can anyone let me know that bottom sheet iOS behaviour goes to hide behind the keyboard when i write comment in text input.

![Simulator Screen Shot - iPhone 12 - 2021-11-11 at 17 24 55](https://user-images.githubusercontent.com/71919615/141295451-afc09505-43ba-4f81-a7a7-3a676e778d30.png)
![Simulator Screen Shot - iPhone 12 - 2021-11-11 at 17 24 51](https://user-images.githubusercontent.com/71919615/141295467-5f5d13b0-dec8-4125-9338-fcc072ac27a6.png)

**Comment by StefanoMartella** [comment]
Hi @Zyauddin,

does it happen only on the `TextInput` inside the bottom sheet or whenewer you have a `TextInput` on the bottom side of your screen?

**Comment by Zyauddin** [comment]
> Hi @Zyauddin,
> 
> does it happen only on the `TextInput` inside the bottom sheet or whenewer you have a `TextInput` on the bottom side of your screen?

Hi @StefanoMartella,

it's only happening on the TextInput inside the bottom sheet

**Comment by StefanoMartella** [comment]
Have you tried to use `KeyboardAvoidingView` component from react native? The result should be the following:

<div>
<img src="https://user-images.githubusercontent.com/29805626/142185320-9aee7132-3353-4fde-8fd6-f8705d5d6530.gif" width="40%" />
</div><br />

Code:

```Javascript
import React from 'react';
import {
  SafeAreaView,
  StyleSheet,
  TextInput,
  KeyboardAvoidingView,
} from 'react-native';
import BottomSheet from 'react-native-simple-bottom-sheet';

function App() {
  return (
    <KeyboardAvoidingView
      style={styles.container}
      contentContainerStyle={styles.contentContainer}
      behavior="position">
      <SafeAreaView style={styles.content}>
        <BottomSheet innerContentStyle={styles.sheetContent}>
          <TextInput placeholder="Put some text here" style={styles.input} />
        </BottomSheet>
      </SafeAreaView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
  },
  contentContainer: {
    flexGrow: 1,
    backgroundColor: '#efefef',
  },
  content: {
    flexGrow: 1,
  },
  sheetContent: {
    paddingBottom: 48,
  },
  input: {
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dedede',
  },
});

export default App;
```

**Comment by FezVrasta** [comment]
A better looking solution is to only wrap the BottomSheet component with:

```
<KeyboardAvoidingView
  style={{
    flexGrow: 1,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  }}
  contentContainerStyle={{ flexGrow: 1 }}
  behavior="position"
>
```

This way the content outside the modal will not shift too.
